let config = {
    active_listener: 3,
    areas_of_agreement: 5,
    ask_for_feedback: 3,
    bee_brief: 6,
    brainstormer: 5,
    check_for_understanding: 2,
    clarifing_question: 4,
    decide: 5,
    define_the_problem: 7,
    disagreement_solver: 6,
    encourageing_knowlege: 7,
    give_feedback: 7,
    helper: 5,
    ideas_evaluation: 7,
    info_shareer: 4,
    mic_earned: 5,
    muting_maestro: 2,
    norms_meeting: 5,
    notes_master: 6,
    online_tools: 6,
    problem_pauser: 5,
    questions: 3,
    ready_headset_go: 4,
    resource_vs_impact: 6,
    screenshare: 2,
    stay_on_topic: 4,
    teacher: 8,
    time_earning: 6,
    to_do_tracker: 5,
    zen_enviroment: 6
}

module.exports = config;